### PR TITLE
Made the toolbar a little bit more flat

### PR DESCRIPTION
**Pull request by elzekool**
Made the toolbar a little more flat by removing some borders and adding some padding/margins, etc. 

screenshot from 2016-05-17 21-06-52

### CODE REVIEW

**Comment by barryvdh** [comment]
Cool, tab headers do seem a bit thin now, but hey, I'm not a designer :P

**Comment by barryvdh** [comment]
Just pulled down in my branch, tabs look better then in the screenshot :) Bit high for my taste, but guess that's just matter of personal taste.

**Comment by elzekool** [comment]
I predicted you would find it a little big, I put my inspiration from the Zend Toolbar and the Symfony toolbar, both about 40px high. I think it's more in line with the average navigation height in Magento backend, and less "developer" style.

**Comment by elzekool** [comment]
@barryvdh Are you ok with merging it?

**Comment by barryvdh** [comment]
Yes

**Comment by barryvdh** [comment]
Merged :)

**Comment by barryvdh** [comment]
I think the height is pretty good when collapsed, just when opened, it seems a bit unnecessary large in contrast with the rest below.

**Pull request merged**
